version: '3'

services:
  postgres_db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_rest_golang:
    container_name: api-rest-golang
    build:
      context: .
      dockerfile: Dockerfile

    restart: on-failure

    env_file:
      - .env
    ports:
      - "3500:3500"

    depends_on:
      - postgres_db

volumes:
  postgres_data:
