apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-cx
  namespace: cx-team
spec:
  rules:
    - host: "api-cx.dito.com.br"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-cx
                port:
                  number: 80
